CREATE TABLE BALANCE_SHEET(
PRODUCT_ID INTEGER NOT NULL,
PRODUCT_NAME VARCHAR(50),
BANK_NAME VARCHAR(50),
TOTAL_AMOUNT INTEGER,
STAGE_NUMBER INTEGER,
ANNUAL_INTEREST_RATE VARCHAR(50),
START_DATE VARCHAR(50),
MONTHLY_PRINCIPAL VARCHAR(50),
MONTHLY_INTEREST VARCHAR(50),
ACCOUNT_BILL_DATE VARCHAR(2),
LAST_PAYMENT_DATE VARCHAR(2),
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID)
);